### ISSUE TITLE
Link quebrado, não encontrei o correto

### ISSUE THREAD

**Issue by GuiiMoraes** [felipefialho/felipefialho.com#15]
No teu texto sobre Trampo remoto, de 10-06-2019, tem um link para o Jira Timer, mas esse link ta quebrado e não achei o link correto pra subir numa a PR

Link no site: https://www.felipefialho.com/blog/sobre-trabalhar-remoto/

Link GH: https://github.com/felipefialho/felipefialho.com/blob/master/content/posts/2015-06-10-sobre-trabalhar-remoto.md#hor%C3%A1rios

Linha: "Uso o Jira Timer para gerir o tempo de trabalho e o quanto foi gasto com cada tarefa."

**Comment by felipefialho** [comment]
Obrigado @GuiiMoraes, esse post já é bem antigo, o Jira Timer morreu já tem uns aninhos :(

https://marketplace.atlassian.com/archive/1214410
